### ISSUE TITLE
No call in contig when a double peak exists in one ab1 file

### ISSUE THREAD

**Issue by KMBarton** [roblanf/sangeranalyseR#15]
In make.consensus.seqs I sometimes see many single base pair gaps randomly throughout a sequence. This seems to occur when there are double peaks in one of the ab1 files, even when the corresponding base in the other file is of sufficient quality to call. Image 1 is the fasta file with the make.consensus.seqs contig above and the comparator program contig below. Four intermittent bases are missing in the top contig that were able to be called in the lower contig. Image 2 corresponding ab1 chromatogram for these sequences.

Image 1
![020202_8_fas_1](https://cloud.githubusercontent.com/assets/19339270/20823473/5e90ef32-b8a8-11e6-9f84-382f2bfde8b5.jpg)

Image 2
![020202_8_cg_1](https://cloud.githubusercontent.com/assets/19339270/20823480/6941c938-b8a8-11e6-9396-375ebfdc72ba.jpg)

**Comment by roblanf** [comment]
Hi Kirston,

As with the other issue - can you let me know exactly what you're doing to get these sequences, alignments, and chromatograms.

I have the data you sent me, but when I run ```make.consensus.seqs()``` on your folder of data (with default settings), I get the sequence above without the gaps you are seeing. So I'm not very sure what you're doing. 

Specifically, I am doing this:

```
input.folder = "/0202/0202_ab1" # this is the data you sent me
forward.suffix = "_F.ab1"
reverse.suffix = "_R.ab1"
cs = make.consensus.seqs(input.folder, forward.suffix, reverse.suffix)
```

And the sequence I get for 0202-8HT, corresponding to the window you posted above, is the first line below. The second line has the missing bases in your post as stars (*), that I can't recreate when running sangeranalyseR

```
GTGG-AAAATGACATGGTAGAACAGATGCATGAGGATATAATCAGTCTATGGGATCAAAGTT
GTGG-AAAATGA*ATGGT*GAACAGATGCATGAGGATATAATCAGTCTATGGGA*CAAAGTT
```

If you can show me how to recreate the issue from your data, then we can go from there. Alternatively, if you run the code above and get the same issue you had before, then you are likely using an old version of sangeranalyseR. In this case, you should update sangeranalyseR and all of the dependencies and try again.

Rob
