### ISSUE TITLE
Beginning AAAAA sequence not correctly called

### ISSUE THREAD

**Issue by KMBarton** [roblanf/sangeranalyseR#16]
Our sequencing region of interest begins with a run of A's. In some contigs, make.consensus.seqs does not call this series of A's correctly when the comparator program does and they seem to be visible in the chromatogram. Image 1 fasta file with the make.consensus.seqs contig on top and the contig from the comparator program below. In this case the initial two A's were called as GGs. Image 2 The chromatogram for the corresponding region.

Image 1
![020202_30_fas_1](https://cloud.githubusercontent.com/assets/19339270/20823579/a18fe954-b8a9-11e6-9e75-ab5c702322a5.jpg)

Image 2
![020202_30_cg_1](https://cloud.githubusercontent.com/assets/19339270/20823683/8df0c656-b8aa-11e6-808e-32d4008c6534.jpg)

[020202_30_cg_1.pdf](https://github.com/roblanf/sangeranalyseR/files/626417/020202_30_cg_1.pdf)

**Comment by roblanf** [comment]
Hi Kirston,

Can you, if possible, post the exact commands you are using to get this sequence. 

It helps if I can start by reproducing precisely what you did. 

If you can just cut-and-paste from whatever script you were using, I can start from there and figure it out.

Cheers,

Rob

**Comment by roblanf** [comment]
Update - running these commands on your data:


```
input.folder = "/0202/0202_ab1" # this is the data you sent me
forward.suffix = "_F.ab1"
reverse.suffix = "_R.ab1"
cs = make.consensus.seqs(input.folder, forward.suffix, reverse.suffix)
```

I get the following sequence for 30HT:

```
TGTGGAAAAATG
```

I.e. it calls 5 A's, as you were expecting. 

Also note that in the example you posted, it is not calling A's as G's - it appears that it just called fewer A's, and you have mis-aligned the sequences in your example. Specifically, the ATGTGG sequence in 30HT should align with that from the 3HT below it. The only difference is in your example 2 fewer A's were called in 30HT than in 3HT. I can't recreate this in sangeranalyseR, but it's worth noting anyway that accurately calling homopolymer runs like this is tricky at the best of times. 

It seems to me like you might be using old versions of sangeranalyseR and its dependencies. Best thing is probably to update everything and try again. Let me know here how you get on.

Rob
