### ISSUE TITLE
idclusters bug

### ISSUE THREAD

**Issue by roblanf** [roblanf/sangeranalyseR#18]
From a user: 

Dear Rob,
 
I read with interest your method sangeranalyseR which I think might be useful for me research.
 
I tried the package using the accompanying test data (https://github.com/roblanf/sangeranalyseR). I experience a problem with the merge.reads (see r console output below) indicating an error in the IdClusters.
 
Do you have any idea how I can solve this error?
 
Thank you in advance.
 
Best regards,
 
Wim
 
```
> fwd = readsangerseq("H:/03_projects/02_Analyse/AnoID/test_data/Drosophila_melanogaster/BBDCN941-10[C_LepFolF,C_LepFolR]_F.ab1")
> rev = readsangerseq("H:/03_projects/02_Analyse/AnoID/test_data/Drosophila_melanogaster/BBDCN941-10[C_LepFolF,C_LepFolR]_R.ab1")
> 
> fwd = primarySeq(fwd)
> rev = primarySeq(rev)
> 
> rev = reverseComplement(rev)
> 
> reads = DNAStringSet(c(as.character(fwd), as.character(rev)))
> names(reads) = c('fwd', 'rev')
> 
> merged.reads = merge.reads(reads)
[1] "Aligning reads"
[1] "Calling consensus sequence"
[1] "Calculating differences between reads and consensus"
Error in IdClusters(dist, asDendrogram = TRUE, processors = processors,  : 
  unused argument (asDendrogram = TRUE)
```

**Comment by roblanf** [comment]
Best guess (no time to check right now) is that DECIPHER has changed the way IdClusters works. At least, that's the first place to check. 

Also add TravisCI to the todo list to try and avoid too much more of this.

**Comment by PrernaDas** [comment]
Hi Rob

I also get the same issue, when I run the example you have on here. 


> merged.reads = merge.reads(reads)
[1] "Aligning reads"
[1] "Calling consensus sequence"
[1] "Calculating differences between reads and consensus"
Error in IdClusters(dist, asDendrogram = TRUE, processors = processors,  : 
  unused argument (asDendrogram = TRUE)


-Prerna

**Comment by roblanf** [comment]
Fixed here: https://github.com/roblanf/sangeranalyseR/commit/77388d58e86716bd06b4db4a75969b3503086d93

I can only apologise for the long delay. Thanks for your patience.

**Comment by PrernaDas** [comment]
Hi Rob,

I tried using the function, but again get the same error with the test data. Can you please look into this again,
> ? merge.reads
> merged.reads <- merge.reads(reads)
[1] "Aligning reads"
[1] "Calling consensus sequence"
[1] "Calculating differences between reads and consensus"
Error in IdClusters(dist, asDendrogram = TRUE, processors = processors,  : 
  unused argument (asDendrogram = TRUE)

Much thanks,
Prerna

**Comment by PrernaDas** [comment]
Hi Rob,
I get a new error now:(. Can you please look into this..
Much thanks,
Prerna


> fwd = readsangerseq("BBDCN941-10[C_LepFolF,C_LepFolR]_F.ab1")
> rev = readsangerseq("BBDCN941-10[C_LepFolF,C_LepFolR]_R.ab1")
> 
> fwd = primarySeq(fwd)
> rev = primarySeq(rev)
> 
> # don't forget to reverse complement
> rev = reverseComplement(rev)
> 
> # this gives us an unaligned set of the reads we wish to merge
> reads = DNAStringSet(c(as.character(fwd), as.character(rev)))
> names(reads) = c('fwd', 'rev')
> 
> merged.reads = merge.reads(reads)
[1] "Aligning reads"
[1] "Calling consensus sequence"
[1] "Calculating differences between reads and consensus"
Error in diffs[, 2] : subscript out of bounds
In addition: Warning message:
In mclapply(aln, n.pairwise.diffs, subject = consensus, mc.cores = processors) :
  all scheduled cores encountered errors in user code

**Comment by PrernaDas** [comment]
Hi Rob,
I get a new error now:(. Can you please look into this..
Much thanks,
Prerna

############################################################################
fwd = readsangerseq("BBDCN941-10[C_LepFolF,C_LepFolR]_F.ab1")
rev = readsangerseq("BBDCN941-10[C_LepFolF,C_LepFolR]_R.ab1")
fwd = primarySeq(fwd)
rev = primarySeq(rev)
reads = DNAStringSet(c(as.character(fwd), as.character(rev)))
names(reads) = c('fwd', 'rev')
merged.reads = merge.reads(reads)
[1] "Aligning reads"
[1] "Calling consensus sequence"
[1] "Calculating differences between reads and consensus"
Error in diffs[, 2] : subscript out of bounds
In addition: Warning message:
In mclapply(aln, n.pairwise.diffs, subject = consensus, mc.cores = processors) :
all scheduled cores encountered errors in user code
