### ISSUE TITLE
reading abif bug

### ISSUE THREAD

**Issue by roblanf** [roblanf/sangeranalyseR#19]
From a user:

I recently installed sangeranalyseR from github, but I'm having trouble reading in my ab1 file. When I use read.abif(seq.filepath), I get the following error message: Warning message:
In read.abif(seq.filepath) : unimplemented legacy type found in file.
Do you have any idea what may be causing this/how to fix it? Your package looks like it would be very helpful for repeatable analysis of Sanger sequences from raw seqs to final contigs.
I can send the ab1 file in question if you'd like.

**Comment by roblanf** [comment]
This is an issue beyond the scope of sangeranalyseR. Suggestion is to contact the authors of sangerseqR to see if they are willing to write a new parser.

**Comment by Sofi-tofi** [comment]
Hello Roblanf, I have the same issue in my sangeranalyseR scrip. Can you give me any tips for fix it?

Thank yuo

**Comment by roblanf** [comment]
Hi @Sofi-tofi - same tip as above! If sangerseqR can't read your file, then I'm afraid we can't help right now. What you need to do is go to the developer of sangerseqR to see if they are willing to develop a parser for your file type.

**Comment by chagas98** [comment]
Hello,

Anyway, I suppose you can still read "important" data from your file. I was diving into the source code from the read.abif function (https://github.com/jonathonthill/sangerseqR/blob/master/R/ReadFileFunctions.R) and this warning comprehend just two data types not supported by the package (see element type 12 and 13 in  https://projects.nfstc.org/workshops/resources/articles/ABIF_File_Format.pdf)
