### ISSUE TITLE
make.consensus.seqs - Error when adding arguments

### ISSUE THREAD

**Issue by anniwinckelmann** [roblanf/sangeranalyseR#22]
With the attached set of 30 ab1 files, using this code, creates 15 consensus sequences.
`input.folder = "firstseq"`
`forward.suffix = "-F.ab1"`
`reverse.suffix = "-R.ab1"`
`cs = make.consensus.seqs(input.folder, forward.suffix, reverse.suffix)`

However, some of the files are low quality and I wish to add more arguments to filter these out.
`ref.seq = ("KNNMVEQMHEDIISLWDQSLKPCVKLTPLCVTLNCTDLMNATNTNTTIIYRWRGEIKNCSFNITTSIRDKVQKEYALFYKLDVVPIDNDNTSYRLISCNTSVITQACPKVSFEPIPIHYCAPAGFAILKCNDKKFNGTGPCTNVSTVQCTHGIRPVVSTQLLLNGSLAEEEVVIRSENFTDNAKTIIVQLNESVEINCTRPNNNTRKSIHIGPGRAFYTTGEIIGDIRQAHCNISRAKWNNTLKQIVKKLREQF")`
`cs = make.consensus.seqs(input.folder, forward.suffix, reverse.suffix, ref.aa.seq = ref.seq, max.secondary.peaks = 5)`

Then I get this output and error message:
`[1] "Looking for .ab1 files..."`
`[1] "Grouping 30 files into sets by filename..."`
`[1] "30 of the files matched either the forward or reverse suffixes"`
`[1] "Grouped these into 15 sets of files"`
`[1] "Loading .ab1 files..."`
`[1] "Constructing readsets..."`
`[1] "Building read summaries..."`
`[1] "Filtering readsets with <2 reads..."`
`[1] "After filtering, 10 of 15 readsets remain"`
`[1] "Building consensus sequences..."`
`[1] "Successfully built 10 consensus sequences"`
`[1] "Summarising consensus sequences..."`
`[1] "Aligning consensus sequences..."`
`[1] "Building tree of consensus sequences..."`
`Advarselsbeskeder:`
`1: I .fun(.value[0], ...) :`
`  no non-missing arguments to max; returning -Inf`
`2: I .fun(.value[0], ...) :`
`  no non-missing arguments to min; returning Inf`

Sorry, some of the warning is in Danish. 'Advarselsbeskeder' simply means warning messages.
Using SangeranalyseR 0.1.0

[firstseq.zip](https://github.com/roblanf/sangeranalyseR/files/1001008/firstseq.zip)

**Comment by roblanf** [comment]
Far too late to be useful I'm sure, but these warning messages are safe to ignore. They come from the step where the tree is built, and this is just a facet of building trees in this way.
