### ISSUE TITLE
Error during make.consensus.seqs

### ISSUE THREAD

**Issue by bvecchip** [roblanf/sangeranalyseR#23]
After applying the following command to an input folder containing 4 abi files (file1_R.ab1, file1_F.ab1, file2_R.ab1, and file2_F.ab1), I get an atomic vector error which seems to arise some time after line 94 in merge.reads.R -- ideas?
 
command: cs = make.consensus.seqs(input.folder, forward.suffix, reverse.suffix)

Error in x$consensus : $ operator is invalid for atomic vectors
In addition: Warning message:
In mclapply(valid.readsets, merge.reads, ref.aa.seq = ref.aa.seq,  :
  all scheduled cores encountered errors in user code

**Comment by roblanf** [comment]
Hi All,

Thanks for the ~infinite patience here. The bug should now be fixed (let's see, it works for me) here https://github.com/roblanf/sangeranalyseR/pull/28.

So, if you re-install and re-load the package from here, 

https://github.com/roblanf/sangeranalyseR

it should work. Please let me know either way! I'll close this now (perhaps tempting fate), but reopen if it's still broken for some.

Rob
