### ISSUE TITLE
use a logger

### ISSUE THREAD

**Issue by roblanf** [roblanf/sangeranalyseR#39]
@HowardChao: currently we have too many print statements, and the output is kinda messy (e.g. some of these look like debugging statements).

Let's move to using a proper logger, so we can distinguish info, error, warning, debug, etc.

**Comment by Kuanhao-Chao** [comment]
I use the [logger](https://github.com/daroczig/logger) R package for logging.

- <img width="843" alt="Screen Shot 2020-04-21 at 3 51 33 am" src="https://user-images.githubusercontent.com/26069376/79783162-94492f00-8383-11ea-9479-036a4666e9f2.png">
