### ISSUE TITLE
reverse sequence chromatograms + some questions

### ISSUE THREAD

**Issue by ewysocka** [roblanf/sangeranalyseR#46]
Hello,

I have worked a bit with the previous version of sangeranalyseR. 
The previous version was already very useful and this one looks really impressive now. It's really neat.
I have some questions regarding the parameters that are not present anymore in this version, 
I mean the treatment of secondary peaks. If the secondary peak is above the 1/3 of the primary peak, then the base recovered becomes ambiguous IUPAC nucleotide code, e.g. A and T becomes W ? Or rather the highest scored base is recovered? From what I can see, it is the latter, right?

My another question is about alignment of forward and reverse reads. Does construction of consensus sequences take into account the phred score, e.g. if there is a mismatch between reads but the quality of a base is better in one of them this one is registered in their consensus?

If its OK if I'm a beta tester, I guess there is something wrong with the reverse sequence chromatograms. I've noticed that the sequence letters on the top and trimmed ends of reverse sequences don't match the curves/peaks. It is as if the chromatogram curves were not reversed compliment, only the sequence and marking of the trimmed ends.

Thanks!
Emilia

**Comment by Kuanhao-Chao** [comment]
Hi @ewysocka! Sorry for my late reply. It takes me some time to fix bugs.

1. sangeranalyseR uses IUPAC nucleotide code; therefore A and T will become W. `signalRatioCutoff` parameter is the cutoff ratio of the height of a secondary peak to a primary peak and its default value is 1/3. You can try to set this parameter smaller and there will be more IUPAC nucleotide code in the secondary sequence.
2. All forward and reverse reads will be trimmed first and then be aligned into a contig by `ConsensusSequence` function from `DECIPHER` R package. Therefore, Phred scores are not taken into account when constructing consensus sequences.
3. Thanks for the bug report. We have fixed the bug and match the primary/secondary peaks with the chromatogram peaks. Please check the latest commit on the master branch. 

Thank you so much for trying sangeranalyseR. Please let me know if you have any questions.

**Comment by roblanf** [comment]
@HowardChao, thanks for looking into it and fixing things up. I'm going to add that I've added a new issue as an enhancement (https://github.com/roblanf/sangeranalyseR/issues/48) where we can consider including phred scores for consensus building in the future.
