### ISSUE TITLE
Improve parameter descriptions in docs

### ISSUE THREAD

**Issue by roblanf** [roblanf/sangeranalyseR#51]
some specific parameters: 
 M1TrimmingCutoff, M2CutoffQualityScore, M2SlidingWindowSize, baseNumPerRow, heightPerRow.

but I think a trawl through to find others would also be useful.

In addition, we need a clear description in the package and the docs of the differences between trimming methods.

**Comment by Kuanhao-Chao** [comment]
- [x] Improve parameter descriptions
- [x] clear description in the package and the docs of the differences between trimming methods.
