### ISSUE TITLE
Cannot launch shiny App

### ISSUE THREAD

**Issue by UndressK** [roblanf/sangeranalyseR#54]
I am getting this error when using the launchApp() function to open shiny: 

> Couldn't normalize path in `addResourcePath`, with arguments: `prefix` = 'AdminLTE-2.0.6'; `directoryPath` = 'C:/Users/biocbuild/bbs-3.12-bioc/R/library/shinydashboard/AdminLTE'

the rest of the functions: writeFasta(), generateReport() seem to work fine. So I wonder if anyone else had this issue or it may be related to my R installation. I recently upgraded to R.4.0. I also tried a different shiny app example and that works..
Thanks a lot!

**Comment by Kuanhao-Chao** [comment]
Hi @UndressK ,

Thanks for raising this issue. We'll work on it! If there's any chance you can send me your files off-list (kuanhao.chao@gmail.com) that would really help. We'll only use them for fixing this bug!

Howard

**Comment by Kuanhao-Chao** [comment]
Hi @UndressK! Have you solved the problem yet?

I tried your code and data that you sent to me on my R 4.0.0 environment and the `launchApp ` function works fine. 
I also searched online and there isn't much information about this error. Maybe you can try updating all shiny-related R packages to the newest version. 

Cheers

**Comment by UndressK** [comment]
No, I couldn't.. but I'll keep trying and see if i can fix it.
thanks anyway!

cheers,
Andrés
