### ISSUE TITLE
generateReport failing to open pdf

### ISSUE THREAD

**Issue by camilogarciabotero** [roblanf/sangeranalyseR#57]
Hi @Kuanhao-Chao ,

Thanks for working on this project! This is could be the best open-source alternative to analyze sanger sequences I've ever found on the web! 

I could spot this problem when generating the report of my SA. That is, when running `generateReport()` function on my SA got the following error:

```
Error in pdf(filename, width = 8.5, height = height * numplots) : cannot open file './SangerAlignment/302_M1_groEL/302_M1_groEL_1_F/Chromatogram.pdf'
```

It seems that maybe there is no `.PDF` or it is not being exported correctly. Anyway, It would be great if you have any thoughts to solve it!

Cheers,
Camilo.

**Comment by Kuanhao-Chao** [comment]
Hi @camilogarciabotero,

Sorry for my late reply. I just checked the `generateReport()` function, and it seems that it works fine. If there's any chance you can send me your ab1 files to kuanhao.chao@gmail.com, that would really help. Of course, I'll only use them for fixing this bug!

Cheers,

Kuan-Hao

**Comment by camilogarciabotero** [comment]
Hi @Kuanhao-Chao 

Thanks for your answer. When trying this function as suggested: 

```
generateReport(newSangerRead,
               outputDir = tempdir()
)
```
Worked for me, yet the HTML report is quite different from what the direct report of the function `launchApp()`renders. Is this what the report should look like when using the function?

![image](https://user-images.githubusercontent.com/25586362/92340308-7274ee00-f07f-11ea-8bda-c7f92e054ef1.png)


Also, when using it with another `outpuDir` path, the execution was halted as I mentioned above. I'll try to send the sequences soon.

Thank you,
Camilo.

**Comment by Kuanhao-Chao** [comment]
Hi @camilogarciabotero,

I tested the `generateReport ` function again and found that the function will crash if you give relative path instead of the absolute path. I have fixed this bug in the newest commit. Please rerun your function again and let me know whether it works.

And for the HTML report, the layout of it is different from Shiny apps, but the results stored inside are same as the results in Shiny apps. 

Cheers,

Kuan-Hao

**Comment by camilogarciabotero** [comment]
Hey Kuan-Hao,

Thanks for your support. I got this other message when using a relative path with the last commit version:

```
Quitting from lines 303-318 (SangerRead_Report_ab1.Rmd) 
Error in pdf(filename, width = 8.5, height = height * numplots) : 
  cannot open file './/SangerAlignment/302_M1_groEL/302_M1_groEL_1_F/Chromatogram.pdf'
```

Regards,
Camilo.

**Comment by Kuanhao-Chao** [comment]
Hi @camilogarciabotero 

I fixed the relative path problems in both `writeFasta` and `generateReport` functions and updated it in the latest commit. 
Both `generateReport(sangerAlignment, "./output_directory")` and `writeFasta(sangerAlignment, "./output_directory")` should work correctly now. 

Sorry for my late reply.

cheers, 
Howard
