### ISSUE TITLE
Can sangeranalyseR provides the function of identifying the quality of chromatogram (ab1 file)?

### ISSUE THREAD

**Issue by wanjinhu** [roblanf/sangeranalyseR#59]
hi there, i got a problem want to consult you, hope you can reply me

i have a lot of chromatogram files (ab1 file), so can I use sangeranalyseR to distinguish the quality of these chromatograms? or do I need to remove the poor quality chromatograms before using sangeranalyseR?

thanks

**Comment by Kuanhao-Chao** [comment]
Hi @wanjinhu,

You can use sangeranalyseR to trim reads with low quality scores. There are two trimming methods implemented in sangeranalyseR which are the modified Mott trimming algorithm and the sliding window trimming. Please check the sangeranalyseR documentation: https://sangeranalyser.readthedocs.io/

Cheers,

Howard

**Comment by roblanf** [comment]
@wanjinhu, there are various other things you could also do (beyond trimming) to judge the quality of your reads in sangeranalyseR, e.g.:

1. Look at the mean (or median) Phred score of reads before or after trimming, and remove reads below some threshold.
2. As for 1. but use the number secondary peaks
3. As for 1. but use the number of indels or stop codons (assuming you have an amino acid sequence that you're expecting)

Just some ideas!

Rob

**Comment by wanjinhu** [comment]
thanks, @Kuanhao-Chao @roblanf

**Comment by wanjinhu** [comment]
thanks for the reply, @Kuanhao-Chao @roblanf 
about two trimming methods, "M1" and "M2". they are all based on the chromatogram base qv value, right? 
the formula is "Q = -10 log10 (P)".
 "M1" the default is 0.0001, that means Q value less than 40 could be trimmed;
"M2CutoffQualityScore" and "M2SlidingWindowSize" just like trimmomatic’s sliding window method, the default is 20 and 10. 
my understanding about trim methods is that, they actually using the same basic way, just like the way when we deal with the NGS data. hope my understanding is correct.
if so, using the default value of the trimming methods, "M2" does not seem to work. when i use sangeranalyseR, i have to set stricter parameters, right?
Is my understanding of the trimming methods correct? thanks
