### ISSUE TITLE
Error to align  Sanger file

### ISSUE THREAD

**Issue by varelaes** [roblanf/sangeranalyseR#67]
Hi,

I've tried run my .abi files but it doesn't work. I also tried example data from package but no sucessful. See below the mensage

my_aligned_contigs_ABIfiles <- SangerAlignment(parentDirectory     = "ABI_files/",
                                      suffixForwardRegExp = "_[0-9]+_F+",
                                      suffixReverseRegExp = "_[0-9]+_R+")

**Error in checkMinReadsNum(minReadsNum, errors) : 
  argument "errorTypes" is missing, with no default**

eduardo varela

**Comment by Kuanhao-Chao** [comment]
Hi @varelaes,

I've check the sangeranalyseR example code on the latest master branch, and it works correctly. 
Could you send me your data (kuanhao.chao@gmail.com), so I can check it for you?
If you want to re-install the newest version of sangeranalyseR from github, you can run the following code 

```
library(devtools)
install_github("roblanf/sangeranalyseR")
```

cheers,

Howard
