### ISSUE TITLE
Change documentation for function args?

### ISSUE THREAD

**Issue by odcambc** [roblanf/sangeranalyseR#73]
Thanks for the very useful package! I was having a bit of trouble following the examples in the readme and the documentation before I realized that the function calls had changed, though.

Right now the following example is given in the readme:
```
ACHLO_contigs <- SangerAlignment(ABIF_Directory     = parentDir,
                                 REGEX_SuffixForward = "_[0-9]*_F.ab1$",
                                 REGEX_SuffixReverse = "_[0-9]*_R.ab1$")
```
This throws an "unused arguments" error. I gather the parameter names have changed. The following works for me:
```
ACHLO_contigs <- SangerAlignment(parentDirectory     = parentDir,
                                 suffixForwardRegExp = "_[0-9]*_F.ab1$",
                                 suffixReverseRegExp = "_[0-9]*_R.ab1$")

```
The current version of the beginner's and quick start guides also do not run as written: changing parameter names seems to work, though.

**Comment by Kuanhao-Chao** [comment]
Hi @odcambc ,

I think the sangeranalyseR that you installed is the the old version. Please reinstall sangeranalyseR again and I think it will work. Here is the [installation page](https://sangeranalyser.readthedocs.io/en/latest/content/installation.html).

Howard
