### ISSUE TITLE
Alignment only forward reads

### ISSUE THREAD

**Issue by ryamy** [roblanf/sangeranalyseR#78]
Are there any methods to align only forward sequences? Does `sangeranalyseR` always require both forward and reverse sequence files?

**Comment by Kuanhao-Chao** [comment]
Hi @ryamy,

sangeranalyseR does not require both forward and reverse reads. You can align only forward sequences. Just put all reads you want to align in the same directory and follow the naming regulation. It should work!

Here is the link to the documentation: https://sangeranalyser.readthedocs.io/en/latest/content/advance_user_SangerAlignment_ab1.html

Best,
Kuan-Hao

**Comment by pavlohrab** [comment]
Hi @Kuanhao-Chao ,

I still have an issue while trying to analyse forward reads only:

```r
ERROR [2023-04-28 14:35:04] PARAMETER_VALUE_ERROR
'REGEX_SuffixReverse' must be character type.
DEBUG [2023-04-28 14:35:04]    >> For more information, please run 'object'.
DEBUG [2023-04-28 14:35:04]    >> Run 'object@objectResults@readResultTable' to check the results of each Sanger reads
```

I just didn't input anything to the `REGEX_SuffixReverse` parameter, so it's `NULL`, as a default value. The version of sangeranalyzeR is `1.10.0`

Is there a workaround of error?

Best,
Pavlo

**Comment by Nicfall** [comment]
Anyone have a solution for the error @pavlorhab presented above? I have that same error
