### ISSUE TITLE
Regarding sangeranalyseR package

### ISSUE THREAD

**Issue by Ruddhida** [roblanf/sangeranalyseR#79]
i am getting an error as "trim.mott not found". what could be the reason for that? and how do i rectify it?

looking forward to hearing from you soon.

thanks and regards
Ruddhida
<img width="916" alt="R" src="https://user-images.githubusercontent.com/80348212/145716609-32eaadf0-dea3-402d-9a85-e7a43a5400e6.png">

**Comment by Kuanhao-Chao** [comment]
Hi @Ruddhida,

We do not implement `trim.mott` function in sangeranalyseR. I think the function that you are looking for is `updateQualityParam`. 
Here is the link to the documentation:
https://sangeranalyser.readthedocs.io/en/latest/content/advance_user_SangerRead_ab1.html#updating-sangerread-quality-trimming-parameters

Best,
Kuan-Hao

**Comment by roblanf** [comment]
Just to expand a bit (an sorry for my slow reply here). `trim.mott()` is a function that was in the old (unreleased) version of SangerAnalyser. 

To trim reads with this algorithm (the algorithm is still there, just not the function) you can change the `TrimmingMethod` parameter. 

The default is `TrimmingMethod        = "M1"`, which is the Mott algorithm. The alternative is `TrimmingMethod        = "M2"`, which is the trimmomatic algorithm. 

More details are here: https://sangeranalyser.readthedocs.io/en/latest/content/advance_user_SangerRead_ab1.html, and elsewhere in the documentation.
